/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Management Api
 * Hospital Management System for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: student@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BedStatus
 */
export interface BedStatus {
    /**
     * ID of patient occupying the bed (if any)
     * @type {string}
     * @memberof BedStatus
     */
    patientId?: string;
    /**
     * Status description
     * @type {string}
     * @memberof BedStatus
     */
    description: string;
}

/**
 * Check if a given object implements the BedStatus interface.
 */
export function instanceOfBedStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function BedStatusFromJSON(json: any): BedStatus {
    return BedStatusFromJSONTyped(json, false);
}

export function BedStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BedStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': !exists(json, 'patient_id') ? undefined : json['patient_id'],
        'description': json['description'],
    };
}

export function BedStatusToJSON(value?: BedStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'description': value.description,
    };
}

