/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Management Api
 * Hospital Management System for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: student@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartmentCapacity
 */
export interface DepartmentCapacity {
    /**
     * Maximum number of beds in department
     * @type {number}
     * @memberof DepartmentCapacity
     */
    maximumBeds: number;
    /**
     * Current number of beds in department
     * @type {number}
     * @memberof DepartmentCapacity
     */
    actualBeds: number;
    /**
     * Number of occupied beds in department
     * @type {number}
     * @memberof DepartmentCapacity
     */
    occupiedBeds: number;
}

/**
 * Check if a given object implements the DepartmentCapacity interface.
 */
export function instanceOfDepartmentCapacity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "maximumBeds" in value;
    isInstance = isInstance && "actualBeds" in value;
    isInstance = isInstance && "occupiedBeds" in value;

    return isInstance;
}

export function DepartmentCapacityFromJSON(json: any): DepartmentCapacity {
    return DepartmentCapacityFromJSONTyped(json, false);
}

export function DepartmentCapacityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentCapacity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maximumBeds': json['maximum_beds'],
        'actualBeds': json['actual_beds'],
        'occupiedBeds': json['occupied_beds'],
    };
}

export function DepartmentCapacityToJSON(value?: DepartmentCapacity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maximum_beds': value.maximumBeds,
        'actual_beds': value.actualBeds,
        'occupied_beds': value.occupiedBeds,
    };
}

