/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Management Api
 * Hospital Management System for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: student@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalizationRecord
 */
export interface HospitalizationRecord {
    /**
     * Hospitalization record unique identifier
     * @type {string}
     * @memberof HospitalizationRecord
     */
    id: string;
    /**
     * Hospitalization description
     * @type {string}
     * @memberof HospitalizationRecord
     */
    description: string;
}

/**
 * Check if a given object implements the HospitalizationRecord interface.
 */
export function instanceOfHospitalizationRecord(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function HospitalizationRecordFromJSON(json: any): HospitalizationRecord {
    return HospitalizationRecordFromJSONTyped(json, false);
}

export function HospitalizationRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalizationRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
    };
}

export function HospitalizationRecordToJSON(value?: HospitalizationRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
    };
}

