/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SarsabsimApp {
    }
}
declare global {
    interface HTMLSarsabsimAppElement extends Components.SarsabsimApp, HTMLStencilElement {
    }
    var HTMLSarsabsimAppElement: {
        prototype: HTMLSarsabsimAppElement;
        new (): HTMLSarsabsimAppElement;
    };
    interface HTMLElementTagNameMap {
        "sarsabsim-app": HTMLSarsabsimAppElement;
    }
}
declare namespace LocalJSX {
    interface SarsabsimApp {
    }
    interface IntrinsicElements {
        "sarsabsim-app": SarsabsimApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sarsabsim-app": LocalJSX.SarsabsimApp & JSXBase.HTMLAttributes<HTMLSarsabsimAppElement>;
        }
    }
}
